EasyConnect/urls.py
from django.urls import path, include
from EasyConnect.views import provider_dashboard
from . import views

app_name = 'easyconnect'
urlpatterns = [
    # default views
    path('', views.index, name='index'),
    path('our-story/', views.our_story, name='our-story'),
    path('faqs/', views.faq, name='faq'),
    path('faq/', views.faq, name='faq'),
    path('privacy-policy/', views.privacy_policy, name='privacy-policy'),
    path('splash-page/', views.splash_page, name='splash-page'),
    path('connect/', views.connect, name='connect-with-a-doctor'),
    path('connect-with-a-doctor/', views.connect, name='connect-with-a-doctor'),
    path('connect-2/<uuid:patient_id>', views.connect_2, name='connect-2'),
    path('video-chat/<uuid:patient_id>', views.video_chat, name='video-chat'),


    #loading data
    path('icd10-load/', views.icd10_load, name='icd10-load'),
    path('affiliate-load/', views.affiliate_load, name='affiliate-load'),

    #server health
    path('server-time/', views.server_time, name='server-time'),
    path('connect-timeless/', views.connect_timeless, name='connect-timeless'),

    # in dev
    path('lucky-provider/', views.lucky_provider, name='lucky_provider'),

    # provier side
    path('provider/<uuid:patient_id>', views.provider_view, name='provider-view'),
    path('stats/', views.call_stats, name='call-stats'),
    path('dashboard/', provider_dashboard, name='dashboard'),
    path('accounts/', include("django.contrib.auth.urls")),
    path('accounts/logout/', views.logout_request, name='logout'),
    path('accounts/login/', views.login_request, name='login'),

    # ajax calls
    path('video-token/', views.video_token, name='video-token'),
    path('provider-joined/', views.provider_joined, name='provider-joined'),
    path('provider-in-chat/', views.provider_in_chat, name='provider-in-chat'),
    path('apply-coupon/', views.apply_coupon, name='apply-coupon'),
    path('patient-cost/', views.patient_cost, name='patient-cost'),
    path('square-app-id/', views.square_app_id, name='square-app-id'),
    path('order-nonce/', views.order_nonce, name='order-nonce'),
    path('age-verification/', views.is_eighteen, name='age_verification'),

    #affiliate views
    path('<slug:affiliate_url>/', views.index_affiliate, name='index-affiliate'),
    path('<slug:affiliate_url>/our-story/', views.our_story_affiliate, name='our-story-affiliate'),
    path('<slug:affiliate_url>/faqs/', views.faq_affiliate, name='faq-affiliate'),
    path('<slug:affiliate_url>/privacy-policy/', views.privacy_policy_affiliate, name='privacy-policy-affiliate'),
    path('<slug:affiliate_url>/connect/', views.connect_affiliate, name='connect-with-a-doctor-affiliate'),
    path('<slug:affiliate_url>/connect-with-a-doctor/', views.connect_affiliate, name='connect-with-a-doctor-affiliate'),
    path('<slug:affiliate_url>/connect-2/<uuid:patient_id>', views.connect_2_affiliate, name='connect-2-affiliate'),
    path('<slug:affiliate_url>/video-chat/<uuid:patient_id>', views.video_chat_affiliate, name='video-chat-affiliate'),
]

EasyConnect/views.py
import os
import csv
import json
import uuid

from datetime import datetime, timedelta

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse, HttpResponseNotAllowed
from django.urls import reverse
from django.conf import settings
from django.contrib.auth import logout
from django.db import connection
from django.contrib.auth.models import User

from EasyConnect.forms import PatientForm, SymptomsForm, ProviderForm, PaymentForm, ICD10CodeLoad, \
    AffiliateForm, CouponForm, VitalsForm, PrescriptionProvidedForm
from EasyConnect.models import Patient, Symptoms, ProviderNotes, Appointments, Payment, Icd10, \
    Affiliate, Coupon, Patient_Cost, Vitals, UserPhone

from square.client import Client

from twilio.jwt.access_token import AccessToken
from twilio.jwt.access_token.grants import VideoGrant
from twilio.rest import Client as TwilioRestClient

from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail
from python_http_client.exceptions import HTTPError

import logging

logger = logging.getLogger('app_api')

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def get_affiliate_context(affiliate_url):
    affiliate = None
    if affiliate_url != '':
        affiliate = Affiliate.objects.filter(affiliate_url=affiliate_url).first()

    if not affiliate:
        affiliate = Affiliate.objects.filter(affiliate_name='EasyConnect').first()

    context = {
        'affiliate': affiliate,
    }

    return context


def get_affiliate_object(affiliate_url):
    if affiliate_url:
        affiliate = Affiliate.objects.filter(affiliate_url=affiliate_url).first()
        if affiliate:
            return affiliate

    return Affiliate.objects.filter(affiliate_name='EasyConnect').first()


# Create your views here.
def index(request):
    return index_affiliate(request, '')


def index_affiliate(request, affiliate_url):
    affiliate_url = affiliate_url.lower()
    context = get_affiliate_context(affiliate_url)
    return render(request, 'EasyConnect/index.html', context)


def our_story(request):
    return our_story_affiliate(request, '')


def our_story_affiliate(request, affiliate_url):
    affiliate_url = affiliate_url.lower()
    context = get_affiliate_context(affiliate_url)
    return render(request, 'EasyConnect/our-story.html', context)


def faq(request):
    return faq_affiliate(request, '')


def faq_affiliate(request, affiliate_url):
    affiliate_url = affiliate_url.lower()
    context = get_affiliate_context(affiliate_url)
    return render(request, 'EasyConnect/faq.html', context)


def privacy_policy(request):
    return faq_affiliate(request, '')


def privacy_policy_affiliate(request, affiliate_url):
    affiliate_url = affiliate_url.lower()
    context = get_affiliate_context(affiliate_url)
    return render(request, 'EasyConnect/privacy-policy.html', context)


def splash_page(request):
    return splash_page_affiliate(request, '')


def splash_page_affiliate(request, affiliate_url):
    affiliate_url = affiliate_url.lower()
    context = get_affiliate_context(affiliate_url)
    return render(request, 'EasyConnect/splash-page.html', context)


def connect(request):
    return connect_affiliate(request, '')


def connect_affiliate(request, affiliate_url):
    affiliate_url = affiliate_url.lower()
    if request.method == 'POST':
        # Create a form instance and populate it with data from the request (binding):
        form = PatientForm(request.POST)
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            phone_number = form.cleaned_data['phone_number']
            email = form.cleaned_data['email']
            dob = form.cleaned_data['dob']
            gender = form.cleaned_data['gender']
            zip = form.cleaned_data['zip']
            tos = form.cleaned_data['tos']
            affiliate = get_affiliate_object(affiliate_url=affiliate_url)
            patient = Patient(first_name=first_name,
                              last_name=last_name,
                              phone_number=phone_number,
                              email=email,
                              dob=dob,
                              gender=gender,
                              zip=zip,
                              tos=tos,
                              affiliate=affiliate)
            patient.save()

            patient_cost = Patient_Cost(patient_id=patient.id, cost=affiliate.affiliate_price)
            patient_cost.save()

            # redirect to a new URL:
            if affiliate_url:
                return HttpResponseRedirect(reverse('easyconnect:connect-2-affiliate',
                                                    kwargs={'patient_id': patient.id,
                                                            'affiliate_url': affiliate_url}))
            else:
                return HttpResponseRedirect(reverse('easyconnect:connect-2', args=(patient.id,)))

    # If this is a GET (or any other method) create the default form.
    else:
        form = PatientForm()

    off_hours = is_offhours()

    affiliate = get_affiliate_context(affiliate_url=affiliate_url)

    context = {
        'form': form,
        'off_hours': off_hours,
        'is_holiday': is_holiday(),
    }
    context.update(affiliate)
    return render(request, 'EasyConnect/connect.html', context)


def connect_timeless(request):
    if request.method == 'POST':
        # Create a form instance and populate it with data from the request (binding):
        form = PatientForm(request.POST)
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            phone_number = form.cleaned_data['phone_number']
            email = form.cleaned_data['email']
            dob = form.cleaned_data['dob']
            gender = form.cleaned_data['gender']
            zip = form.cleaned_data['zip']
            tos = form.cleaned_data['tos']
            affiliate = get_affiliate_object(affiliate_url='')

            patient = Patient(first_name=first_name,
                              last_name=last_name,
                              phone_number=phone_number,
                              email=email,
                              dob=dob,
                              gender=gender,
                              zip=zip,
                              tos=tos,
                              affiliate=affiliate)
            patient.save()

            patient_cost = Patient_Cost(patient_id=patient.id, cost=affiliate.affiliate_price)
            patient_cost.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('easyconnect:connect-2', args=(patient.id,)))

    # If this is a GET (or any other method) create the default form.
    else:
        form = PatientForm()

    off_hours = False

    affiliate = get_affiliate_context(affiliate_url='')
    context = {
        'form': form,
        'off_hours': off_hours
    }
    context.update(affiliate)
    return render(request, 'EasyConnect/connect.html', context)


def connect_2(request, patient_id):
    return connect_2_affiliate(request, patient_id, '')


def connect_2_affiliate(request, patient_id, affiliate_url):
    affiliate_url = affiliate_url.lower()
    patient = get_object_or_404(Patient, pk=patient_id)
    patient_cost = Patient_Cost.objects.filter(patient=patient_id).first()
    affiliate_obj = get_affiliate_object(affiliate_url=affiliate_url)

    if not patient_cost:
        logger.info(f'{patient.id} Adding patient cost.')
        patient_cost = Patient_Cost(patient_id=patient.id, cost=affiliate_obj.affiliate_price)
        patient_cost.save()

    payment_errors = None

    # TODO add handling for completed appointments.
    if Appointments.objects.filter(patient_id=patient.id):
        if affiliate_url:
            return HttpResponseRedirect(reverse('easyconnect:video-chat-affiliate',
                                                kwargs={'patient_id': patient.id,
                                                        'affiliate_url': affiliate_url}))
        else:
            return HttpResponseRedirect(reverse('easyconnect:video-chat', args=(patient_id,)))

    if request.method == 'POST':
        logger.info(f'{patient.id} patient submitting payment')
        # Create a form instance and populate it with data from the request (binding):
        symptom_form = SymptomsForm(request.POST)
        payment_form = PaymentForm(request.POST)
        coupon_form = CouponForm(request.POST)
        vitals_form = VitalsForm(request.POST)

        if symptom_form.is_valid() and vitals_form.is_valid() and (payment_form.is_valid() or patient_cost <= 0):
            logger.info(f'{patient.id} forms are valid')

            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            pancreatitis_thyroid_cancer = symptom_form.cleaned_data['pancreatitis_thyroid_cancer']
            allergies = symptom_form.cleaned_data['allergies']
            medications = symptom_form.cleaned_data['medications']
            previous_diagnosis = symptom_form.cleaned_data['previous_diagnosis']

            # get existing object if it exists and update.
            symptom_obj = get_object_data_or_set_defaults(Symptoms.objects.filter(patient_id=patient_id).first())

            height_feet = vitals_form.cleaned_data['height_feet']
            height_inches = vitals_form.cleaned_data['height_inches']

EasyConnect/templates/EasyConnect/chat-widget.html
<!--Start of Tawk.to Script-->
<script type="text/javascript">
var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
(function(){
var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
s1.async=true;
s1.src='https://embed.tawk.to/619e76346bb0760a494433e6/1fl9frfmn';
s1.charset='UTF-8';
s1.setAttribute('crossorigin','*');
s0.parentNode.insertBefore(s1,s0);
})();
</script>
<!--End of Tawk.to Script-->

EasyConnect/templates/EasyConnect/faq.html
{% load static %}
{% load math_filters %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>KellumConnectMD | FAQ</title>
    <link rel="shortcut icon" type="image/png" href="{% get_static_prefix %}EasyConnect/assets/img/favicon-color.png"/>
    <link rel="stylesheet" href="{% get_static_prefix %}EasyConnect/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Antic">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cambay">
    <link rel="stylesheet" href="{% get_static_prefix %}EasyConnect/assets/css/Footer-Dark.css">
    <link rel="stylesheet" href="{% get_static_prefix %}EasyConnect/assets/css/styles.css">
    <link rel="stylesheet" href="{% get_static_prefix %}EasyConnect/assets/css/untitled.css">

    <link rel="stylesheet" href="{% get_static_prefix %}EasyConnect/assets/fonts/ionicons.min.css">
    <link rel="stylesheet" href="{% get_static_prefix %}EasyConnect/assets/css/Social-Icons.css">

    {% include 'EasyConnect/tracking_codes.html' %}
</head>

<body>
    {% include 'EasyConnect/standard_navbar.html' %}
    <div class="d-flex d-sm-flex d-md-flex d-lg-flex d-xl-flex justify-content-center justify-content-sm-center justify-content-md-center justify-content-lg-center justify-content-xl-center"><img src="{% get_static_prefix %}EasyConnect/assets/img/Icon-faq.png"></div>
    <div class="d-flex d-sm-flex d-md-flex d-lg-flex d-xl-flex justify-content-center justify-content-sm-center justify-content-md-center justify-content-lg-center justify-content-xl-center">
        <h1 style="font-family: Antic, sans-serif;font-size: 30px;font-weight: bold;margin-top: 20px;margin-bottom: 24px;">FAQs</h1>
    </div>
    <div style="margin-left: 20%; margin-right: 20%">
        <h1 style="font-family: Antic, sans-serif;font-size: 21px;font-weight: 600;">What do KellumConnectMD online visits mean to me and my family?</h1>
        <p style="font-family: Antic, sans-serif;font-size: 19px;">They are designed to bring you quality primary non-urgent care in an affordable, convenient manner through secure video conferencing. Skip the trip to Urgent Care. Save the cost of an urgent care copay. No leaving home, work or school.</p>
        <h1
            style="font-family: Antic, sans-serif;font-size: 21px;font-weight: 600;">What can I use an KellumConnectMD online visit for?</h1>
            <p style="font-family: Antic, sans-serif;font-size: 19px;">Many common non-urgent ailments can be addressed: Cold and flu symptoms, sore throat, cough, allergies and sinus
                infection, nausea and vomiting, diarrhea, upper respiratory infections, urinary tract infections, pink eye, rashes
                and minor skin irritations.</p>
            <h1 style="font-family: Antic, sans-serif;font-size: 21px;font-weight: 600;">Does KellumConnectMD take the place of my regular Primary Care Provider?</h1>
            <p style="font-family: Antic, sans-serif;font-size: 19px;">No. KellumConnectMD cannot be used to diagnose, treat or manage chronic conditions. It is a concierge self-pay
                service provided as a convenient, affordable alternative to long waits, time away from home/work/school, and rising costs.</p>
            <h1
                style="font-family: Antic, sans-serif;font-size: 21px;font-weight: 600;">How much does a KellumConnectMD online visit cost?</h1>
                <p style="font-family: Antic, sans-serif;font-size: 19px;">${{ affiliate.affiliate_price|div:100 }}, payable by credit card prior to the start of the visit.</p>
                <h1 style="font-family: Antic, sans-serif;font-size: 21px;font-weight: 600;">When are KellumConnectMD online visits available?</h1>
                <p style="font-family: Antic, sans-serif;font-size: 19px;">Visits are available 7-days a week from 8:00 AM to 8:00 PM Central Time.</p>
                <h1 style="font-family: Antic, sans-serif;font-size: 21px;font-weight: 600;">What happens after I book my KellumConnectMD online visit and make my payment?</h1>
                <p style="font-family: Antic, sans-serif;font-size: 19px;">You will be taken to the secure Video Chat page. On this page you’ll be able to select a pharmacy near you
                    while you wait for the doctor to join you. Be sure to select the “Click to Start Video Chat” button to be sure your
                    video camera and audio are working. The doctor will confirm the Pharmacy of your choice during your visit.</p>
                <h1 style="font-family: Antic, sans-serif;font-size: 21px;font-weight: 600;">Are KellumConnectMD online visits covered by my insurance?</h1>
                <p style="font-family: Antic, sans-serif;font-size: 19px;">No. KellumConnectMD does not contract with Health Plans. It is a self-pay concierge service provided as a
                    convenient, affordable alternative for your non-urgent care needs.</p>
                <h1 style="font-family: Antic, sans-serif;font-size: 21px;font-weight: 600;">What medications can be prescribed during an KellumConnectMD visit?</h1>
                <p style="font-family: Antic, sans-serif;font-size: 19px;">KellumConnectMD providers may offer prescriptions for a wide range of ailments including, but not limited
                    to, drug classes such as antibiotics and antihistamines. If a provider does prescribe medication, he/she will usually limit
                    the supply to no more than 10 days. Remember that KellumConnectMD does not take the place of your Primary Care Provider
                    or specialist, and will not issue prescriptions for:</p>
                <ul style="font-size: 19px;font-family: Antic, sans-serif;">
                    <li>General medicine refills (for chronic conditions)</li>
                    <li>Extended care (beyond a 10-day treatment)</li>
                    <li>Substances controlled by the DEA, for non-therapeutic use, and/or those which may be harmful (potential for
                        abuse or addiction).</li>
                </ul>
                <p class="d-xl-flex" style="font-family: Antic, sans-serif;font-size: 19px;margin-bottom: 27px;">For a current list of DEA controlled substances, visit:&nbsp;
                    <a href="http://www.deadiversion.usdoj.gov/schedules/"><span style="text-decoration: underline;">http://www.deadiversion.usdoj.gov/schedules/</span>
                    </a>
                </p>
                <h1 style="font-family: Antic, sans-serif;font-size: 21px;font-weight: 600;">What pharmacies can I use with KellumConnectMD online visits?</h1>
                <p style="font-family: Antic, sans-serif;font-size: 19px;">KellumConnectMD can send prescriptions to any pharmacies you currently use.</p>
                <h1 style="font-family: Antic, sans-serif;font-size: 21px;font-weight: 600;">What are the system requirements for my Desktop/Laptop or smartphone?</h1>
                <p style="font-family: Antic, sans-serif;font-size: 19px;">On a Desktop or Laptop you will need:</p>
                <ul style="font-size: 19px;font-family: Antic, sans-serif;">
                    <li>A computer running MacOS, Windows, or Linux operating system</li>
                    <li>Google Chrome, Firefox, Microsoft Edge or Safari browser</li>
                    <li>The minimum internet speed of 2MB/s upload speed and 2MB/s download speed is recommended. Otherwise the doctor
                        will not be able to see you clearly.</li>
                </ul>
                <p style="font-family: Antic, sans-serif;font-size: 19px;">On an iPhone or iPad you will need:</p>
                <ul style="font-size: 19px;font-family: Antic, sans-serif;">
                    <li>Safari web browser</li>
                    <li>The minimum internet speed of 2MB/s upload speed and 2MB/s download speed is&nbsp;recommended. Otherwise the doctor
                        will not be able to see you clearly.</li>
                </ul>
                <p style="font-family: Antic, sans-serif;font-size: 19px;">On other smartphones and tablets you will need:</p>
                <ul style="font-size: 19px;font-family: Antic, sans-serif;">
                    <li>Google Chrome, Firefox or Microsoft Edge Mobile</li>
                    <li>The minimum internet speed of 2MB/s upload speed and 2MB/s download speed is recommended. Otherwise the doctor
                        will not be able to see you clearly.</li>
                </ul>
                <h1 style="font-family: Antic, sans-serif;font-size: 21px;font-weight: 600;">Is KellumConnectMD HIPAA Compliant?</h1>
                <p style="font-family: Antic, sans-serif;font-size: 19px;">Yes, the KellumConnectMD online site follows rules of HIPAA compliance. We do not share personal information
                    with other sites unless specifically authorized by you. KellumConnectMD is not responsible for the privacy policies of any
                    site linked to this website and not wholly-owned and controlled by KellumConnectMD, its affiliates and subsidiaries. We
                    aim to work with trusted partners and organizations which are also bound by state and federal laws governing
                    privacy and security; however, we encourage you to be aware when you leave our site and to review any privacy policy
                    of a non-KellumConnectMD site.</p>
                <h1 style="font-family: Antic, sans-serif;font-size: 21px;font-weight: 600;">Need technical support?</h1>
                <p style="font-family: Antic, sans-serif;font-size: 19px;">Email&nbsp;<a href="mailto:z.dickdon@kellummd.com">z.dickdon@kellummd.com</a>.</p>
    </div>
    <div class="justify-content-center align-items-center align-self-center orange-box">
        <div class="d-xl-flex justify-content-xl-center">
            <h1 class="text-center" style="font-weight: normal;color: rgb(255,255,255);padding-top: 10px;font-family: Antic, sans-serif;">Skip the line, Go online.</h1>
        </div>
        <div class="text-center">
            <p style="background-color: rgba(0,0,0,0);color: #ffffff;font-size: 20px;font-family: Antic, sans-serif;">A doctor is ready to chat right now.</p>
        </div>
        <div class="d-flex d-sm-flex d-md-flex d-lg-flex d-xl-flex justify-content-center justify-content-sm-center justify-content-md-center justify-content-lg-center justify-content-xl-center"><button class="btn btn-primary border rounded-0 shadow-sm button-white" id="orange-box-button" type="button"><a id="orange-box-link" class="link-base orange-btn" href="{% if affiliate.affiliate_url %}{% url 'easyconnect:connect-with-a-doctor-affiliate' affiliate.affiliate_url %}{% else %}{% url 'easyconnect:connect-with-a-doctor' %}{% endif %}">Connect now for just ${{ affiliate.affiliate_price|div:100 }}</a></button></div>
        <div class="text-center">
            <p style="background-color: rgba(0,0,0,0);color: #ffffff;font-family: Antic, sans-serif;">No insurance required</p>
        </div>
    </div>
    {% include 'EasyConnect/standard-footer.html' %}
</body>

</html>

EasyConnect/templates/EasyConnect/provider_navbar.html
{% load static %}
    <nav class="navbar navbar-light navbar-expand-md fixed-top d-xl-flex" style="background-color: #ffffff;filter: blur(0px) grayscale(0%) hue-rotate(0deg) invert(0%) saturate(100%) sepia(0%);">
        <div class="container">
            <div><a class="navbar-brand" href="{% url 'easyconnect:dashboard' %}" style="margin-right: 0;"><img src="{% get_static_prefix %}EasyConnect/assets/img/Logo-nav.png" alt="Easy Connect MD logo" style="margin-left: 0;"><br></a></div><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1" style="margin-left: 14px;padding: 0;padding-right: 7px;padding-left: 6px;margin-top: 0;height: 40px;margin-bottom: -11px;"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="nav navbar-nav ml-auto" style="font-size: 22px;margin: 0;">
                    {%  if user.is_authenticated %}
                        <li class="nav-item" role="presentation" style="padding: 0; padding-right: 13px;"><a class="nav-link navi-item" href="{% url 'easyconnect:logout' %}">Logout</a></li>
                    {% else %}
                        <li class="nav-item" role="presentation"><a class="nav-link navi-item" href="{% url 'easyconnect:login' %}">Login</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

<div class="collapse navbar-collapse" id="navcol-1">
                <ul class="nav navbar-nav ml-auto" style="font-size: 22px;margin: 0;">
                    <li class="nav-item" role="presentation" style="padding: 0; padding-right: 13px;"><a class="nav-link navi-item our-story-hack" href="{% url 'easyconnect:our-story' %}">Our Story</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link navi-item" href="{% url 'easyconnect:faq' %}">FAQs</a></li>
                    <li class="nav-item" role="presentation" style="margin-right: -41px;"><button class="btn btn-primary border rounded-0 button-white" type="button"><a id="nav-button" class="link-base button-transparent" href="{% url 'easyconnect:connect-with-a-doctor' %}">Book Now</a></button></li>
                </ul>
            </div>

EasyConnect/templates/EasyConnect/standard_navbar.html
{% load static %}
    <nav class="navbar navbar-light navbar-kcmd navbar-expand-md fixed-top bg-body-tertiary">
        <a class="navbar-brand" href="{% if affiliate.affiliate_url %}{% url 'easyconnect:index-affiliate' affiliate.affiliate_url %}{% else %}{% url 'easyconnect:index' %}{% endif %}" style="margin-right: 0;"><img src="{% get_static_prefix %}{{ affiliate.affiliate_logo }}" alt="Easy Connect MD logo" style="margin-left: 0;"><br></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto me-2" style="font-size: 22px;">
                <li class="nav-item" role="presentation" style="padding: 0; padding-right: 13px;">
                    <a class="nav-link navi-item our-story-hack" href="{% if affiliate.affiliate_url %}{% url 'easyconnect:index-affiliate' affiliate.affiliate_url %}{% else %}{% url 'easyconnect:index' %}{% endif %}">
                        Home
                    </a>
                </li>
                <li class="nav-item" role="presentation" style="padding: 0; padding-right: 13px;">
                    <a class="nav-link navi-item our-story-hack" href="{% if affiliate.affiliate_url %}{% url 'easyconnect:our-story-affiliate' affiliate.affiliate_url %}{% else %}{% url 'easyconnect:our-story' %}{% endif %}">
                        Our Story
                    </a>
                </li>
                <li class="nav-item" role="presentation">
                    <button class="btn btn-primary border rounded-0 button-white" type="button">
                        <a id="nav-button" class="link-base button-transparent" href="{% if affiliate.affiliate_url %}{% url 'easyconnect:connect-with-a-doctor-affiliate' affiliate.affiliate_url %}{% else %}{% url 'easyconnect:connect-with-a-doctor' %}{% endif %}">
                            Book Now
                        </a>
                    </button>
                </li>
            </ul>
        </div>
    </nav>

EasyConnect/templates/EasyConnect/tracking_codes.html
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-38VE55R5R3"></script>
<script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'G-38VE55R5R3');
</script>